#!/bin/bash

# Author:   Kyle Terrien (KlipperKyle)
# Date:     2014-01-14

function fatal {
    echo "$0: $@" >&2
    exit 1
}

function show_help {
    echo "$0: Usage:" >&2
    echo "$0" >&2
    echo "" >&2
    echo "Converts all markdown files into HTML files" >&2
    exit 2
}

function convert_file {
    # Expects 2 filenames: markdown source, HTML output
    cat > "$2" << END_HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd"><html>
<head>
<title>$2</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
$(markdown "$1")
</body>
</html>
END_HTML
}

# Did the user request help?
if [ x"$@" = x"--help" -o x"$@" = x"-h" ] ; then
    show_help
fi

# Check for markdown
type markdown &> /dev/null || fatal "Cannot find markdown"

extension="md"              # Extension of Markdown sources
sources="*.$extension"      # Filter for the Markdown sources

indexfiles=""

# Check for updated markdown source and convert each
for file in $sources ; do
    newfile="${file%.$extension}.html"
    if [ ! -e "$newfile" -o "$file" -nt "$newfile" ]; then
        # Only convert the file if the HTML D.N.E or if the source is newer
        # than the HTML output.
        echo "Converting $file to $newfile"
        convert_file "$file" "$newfile"
    fi
    # Add link to index.html
    indexfiles="${indexfiles}<li><a href=\"${newfile}\">${newfile}</a></li>"$'\n'
done

# Write the index page
cat > index.html << END_HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd"><html>
<html>
<head>
<title>$(pwd)</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<h1>Index of $(pwd)</h1>

<hr>
<ul>
$indexfiles
</ul>
</body>
</html>
END_HTML

echo "Created index.html"

# vim: et ts=4 sw=4 :
